In [65]:
import os
import pandas as pd
from datetime import datetime 
import numpy as np

In [66]:
filename  = '/data/juma/data/ids18/CSVs/WS/Friday-16-02-2018/Friday-16-02-2018.pcap_Flow.csv'
df = pd.read_csv(filename, usecols=['Flow ID','Src IP','Dst IP','TimestampMCS'])

MCS_IN_SEC = 1000000

g = df.groupby(['Flow ID'])
flowLC = g.agg({'Flow ID':'count','Src IP':np.max,'Dst IP':np.min,'TimestampMCS':[np.min,np.max]})


flowLC['DurationMCS'] = (flowLC[('TimestampMCS','amax')] - flowLC[('TimestampMCS','amin')])
flowLC['DurationMCS'] = flowLC['DurationMCS'].astype(float)
flowLC['DurationSEC'] = flowLC['DurationMCS']/MCS_IN_SEC
flowLC = flowLC.sort_values(by=['DurationMCS'],ascending=False)

flowLC.to_csv(filename.replace('.pcap_Flow.csv','.Flow_Duration_small.csv'))

In [67]:
flowLC['DurationM']=flowLC['DurationSEC']/60.

In [68]:
flowLC.head()

                                                  Dst IP      TimestampMCS  \
                                                    amin              amin
Flow ID
131.202.242.193-172.31.69.25-35605-22-6     172.31.69.25  1518784015181877
172.31.66.116-192.229.163.25-49698-443-6  192.229.163.25  1518784655126374
172.31.68.21-52.84.144.173-49706-443-6     52.84.144.173  1518784653333353
172.31.66.109-23.196.102.76-49687-443-6    23.196.102.76  1518784647733540
172.31.65.45-23.46.60.234-49739-443-6       23.46.60.234  1518784654457053
172.31.66.122-23.218.38.23-49700-443-6      23.218.38.23  1518784655255074
172.31.66.61-52.84.128.225-49723-443-6     52.84.128.225  1518784655557119
172.31.65.118-52.84.139.238-49710-443-6    52.84.139.238  1518784655029490
172.31.68.21-52.84.139.141-49707-443-6     52.84.139.141  1518784653334853
172.31.69.6-108.174.10.14-49738-443-6      108.174.10.14  1518784656989684
172.31.66.99-108.174.10.14-49272-443-6     108.174.10.14  1518784661764983
172.31.66.122-94.31.29.64-49724-443-6        94.31.29.64  1518784657986522
172.31.66.46-94.31.29.64-49248-443-6         94.31.29.64  1518784658382791
172.31.66.40-94.31.29.64-49712-443-6         94.31.29.64  1518784660225144
172.31.66.91-94.31.29.64-49721-443-6         94.31.29.64  1518784660337031
172.31.64.29-94.31.29.64-49735-443-6         94.31.29.64  1518784667344769
172.31.66.98-94.31.29.64-49708-443-6         94.31.29.64  1518784673996931
172.31.66.37-192.161.156.1-49700-443-6     192.161.156.1  1518784673395482
172.31.66.91-192.161.156.1-49705-443-6     192.161.156.1  1518784658326348
172.31.66.122-192.161.156.1-49707-443-6    192.161.156.1  1518784656089808

                                                           Flow ID  \
                                                      amax   count
Flow ID
131.202.242.193-172.31.69.25-35605-22-6   1518784460837062       2
172.31.66.116-192.229.163.25-49698-443-6  1518784771430532       2
172.31.68.21-52.84.144.173-49706-443-6    1518784769592637       2
172.31.66.109-23.196.102.76-49687-443-6   1518784763861027       2
172.31.65.45-23.46.60.234-49739-443-6     1518784770551507       2
172.31.66.122-23.218.38.23-49700-443-6    1518784771208654       2
172.31.66.61-52.84.128.225-49723-443-6    1518784771377174       2
172.31.65.118-52.84.139.238-49710-443-6   1518784770692345       2
172.31.68.21-52.84.139.141-49707-443-6    1518784768577528       2
172.31.69.6-108.174.10.14-49738-443-6     1518784770552835       2
172.31.66.99-108.174.10.14-49272-443-6    1518784771986662       2
172.31.66.122-94.31.29.64-49724-443-6     1518784764847735       2
172.31.66.46-94.31.29.64-49248-443-6      1518784765025623       2
172.31.66.40-94.31.29.64-49712-443-6      1518784765062828       2
172.31.66.91-94.31.29.64-49721-443-6      1518784764404015       2
172.31.64.29-94.31.29.64-49735-443-6      1518784765174525       2
172.31.66.98-94.31.29.64-49708-443-6      1518784764760130       2
172.31.66.37-192.161.156.1-49700-443-6    1518784764148239       2
172.31.66.91-192.161.156.1-49705-443-6    1518784749069873       2
172.31.66.122-192.161.156.1-49707-443-6   1518784746766447       2

                                                   Src IP  DurationMCS  \
                                                     amax
Flow ID
131.202.242.193-172.31.69.25-35605-22-6   131.202.242.193  445655185.0
172.31.66.116-192.229.163.25-49698-443-6    172.31.66.116  116304158.0
172.31.68.21-52.84.144.173-49706-443-6       172.31.68.21  116259284.0
172.31.66.109-23.196.102.76-49687-443-6     172.31.66.109  116127487.0
172.31.65.45-23.46.60.234-49739-443-6        172.31.65.45  116094454.0
172.31.66.122-23.218.38.23-49700-443-6      172.31.66.122  115953580.0
172.31.66.61-52.84.128.225-49723-443-6       172.31.66.61  115820055.0
172.31.65.118-52.84.139.238-49710-443-6     172.31.65.118  115662855.0
172.31.68.21-52.84.139.141-49707-443-6       172.31.68.21  115242675.0
172.31.69.6-108.174.10.14-49738-443-6         172.31.69.6  113563151.0
172.31.66.99-108.174.10.14-49272-443-6       172.31.66.99  110221679.0
172.31.66.122-94.31.29.64-49724-443-6       172.31.66.122  106861213.0
172.31.66.46-94.31.29.64-49248-443-6         172.31.66.46  106642832.0
172.31.66.40-94.31.29.64-49712-443-6         172.31.66.40  104837684.0
172.31.66.91-94.31.29.64-49721-443-6         172.31.66.91  104066984.0
172.31.64.29-94.31.29.64-49735-443-6         172.31.64.29   97829756.0
172.31.66.98-94.31.29.64-49708-443-6         172.31.66.98   90763199.0
172.31.66.37-192.161.156.1-49700-443-6       172.31.66.37   90752757.0
172.31.66.91-192.161.156.1-49705-443-6       172.31.66.91   90743525.0
172.31.66.122-192.161.156.1-49707-443-6     172.31.66.122   90676639.0

                                         DurationSEC DurationM

Flow ID
131.202.242.193-172.31.69.25-35605-22-6   445.655185  7.427586
172.31.66.116-192.229.163.25-49698-443-6  116.304158  1.938403
172.31.68.21-52.84.144.173-49706-443-6    116.259284  1.937655
172.31.66.109-23.196.102.76-49687-443-6   116.127487  1.935458
172.31.65.45-23.46.60.234-49739-443-6     116.094454  1.934908
172.31.66.122-23.218.38.23-49700-443-6    115.953580  1.932560
172.31.66.61-52.84.128.225-49723-443-6    115.820055  1.930334
172.31.65.118-52.84.139.238-49710-443-6   115.662855  1.927714
172.31.68.21-52.84.139.141-49707-443-6    115.242675  1.920711
172.31.69.6-108.174.10.14-49738-443-6     113.563151  1.892719
172.31.66.99-108.174.10.14-49272-443-6    110.221679  1.837028
172.31.66.122-94.31.29.64-49724-443-6     106.861213  1.781020
172.31.66.46-94.31.29.64-49248-443-6      106.642832  1.777381
172.31.66.40-94.31.29.64-49712-443-6      104.837684  1.747295
172.31.66.91-94.31.29.64-49721-443-6      104.066984  1.734450
172.31.64.29-94.31.29.64-49735-443-6       97.829756  1.630496
172.31.66.98-94.31.29.64-49708-443-6       90.763199  1.512720
172.31.66.37-192.161.156.1-49700-443-6     90.752757  1.512546
172.31.66.91-192.161.156.1-49705-443-6     90.743525  1.512392
172.31.66.122-192.161.156.1-49707-443-6    90.676639  1.511277

In [71]:
flowLC[(flowLC[('Src IP','amax')]=='172.31.70.23') | (flowLC[('Dst IP','amin')]=='172.31.70.23')]['Label'] = 
suspiciousFlow.head()

Empty DataFrame
Columns: [(Dst IP, amin), (TimestampMCS, amin), (TimestampMCS, amax), (Flow ID, count), (Src IP, amax), (DurationMCS, ), (DurationSEC, ), (DurationM, )]
Index: []

In [4]:
df1['Timestamp'] = pd.to_datetime(df1['Timestamp'],format='%d/%m/%Y %H:%M:%S %p')
df2['Timestamp'] = pd.to_datetime(df2['Timestamp'], format='%d/%m/%Y %H:%M')

In [5]:
print(df1.shape,df2.shape)

(211672, 31) (445909, 155)

In [7]:
df1 = df1.sort_values(by=["Source IP","Source Port","Destination IP","Destination Port", 'Timestamp'])
df1.head()

,Flowid,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Tot pkt,fwd pkt,bwd pkt,...,bwd bytes mean,bytes mean est,fwd bytes mean est,bwd bytes mean est,len std,fwd len std,bwd len std,len std est,fwd len std est,bwd len std est
115322,172.16.0.1-192.168.10.50-45422-80-6,172.16.0.1,45422,192.168.10.50,80,6,2017-07-04 10:30:03,7.000000,4.000000,3.000000,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
24060,172.16.0.1-192.168.10.50-46276-22-6,172.16.0.1,46276,192.168.10.50,22,6,2017-07-04 14:09:01,57.000000,23.000000,34.000000,...,80.74,83.39,87.30,80.74,201.89,133.34,211.27,183.87,133.34,211.27
47931,172.16.0.1-192.168.10.50-46278-22-6,172.16.0.1,46278,192.168.10.50,22,6,2017-07-04 14:09:01,57.000000,23.000000,34.000000,...,80.74,83.39,87.30,80.74,201.89,133.34,211.27,183.87,133.34,211.27
181410,172.16.0.1-192.168.10.50-46280-22-6,172.16.0.1,46280,192.168.10.50,22,6,2017-07-04 14:09:01,56.000000,23.000000,33.000000,...,83.18,84.88,87.30,83.18,203.69,133.34,213.97,185.16,133.34,213.97
211437,172.16.0.1-192.168.10.50-46282-22-6,172.16.0.1,46282,192.168.10.50,22,6,2017-07-04 14:09:01,57.000000,23.000000,34.000000,...,80.74,83.39,87.30,80.74,201.89,133.34,211.27,183.87,133.34,211.27

In [9]:

df2 = df2.sort_values(by=["Source IP","Source Port","Destination IP","Destination Port", 'Timestamp'])
df2[(df2['Destination IP']=='172.16.0.1')& (df2['Destination Port']=='45422') ]

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Std,Active Max,Active Min,Idle Std,Idle Max,Idle Min,Label
70861,172.16.0.1-192.168.10.50-45422-80-6,192.168.10.50,80,172.16.0.1,45422,6,4/7/2017 10:30,16625,2,0,...,-1,0,32,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [24]:
BF_FTP_start = datetime.strptime("2017-07-04 9:20:00 AM", '%Y-%m-%d %H:%M:%S %p')
BF_FTP_end = datetime.strptime("2017-07-04 10:20:00 AM", '%Y-%m-%d %H:%M:%S %p')
after = df2['Timestamp']>=BF_FTP_start
before = df2['Timestamp']<=BF_FTP_end
period = df2[after & before]
period.shape

(89479, 155)

In [31]:
period[(period['Source IP']=='172.16.0.1')].shape

(7877, 155)

In [28]:
period.head()

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Std,Active Max,Active Min,Idle Std,Idle Max,Idle Min,Label
23385,192.168.10.5-103.237.104.66-49896-443-6,103.237.104.66,443,192.168.10.5,49896,6,4/7/2017 9:34,2,2,0,...,-1,0,20,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
287274,192.168.10.5-103.237.104.66-49897-443-6,103.237.104.66,443,192.168.10.5,49897,6,4/7/2017 9:34,4,2,0,...,-1,0,20,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
54727,192.168.10.9-103.25.21.75-3034-443-6,103.25.21.75,443,192.168.10.9,3034,6,4/7/2017 10:05,3,2,0,...,-1,0,20,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
344854,192.168.10.16-103.3.60.59-52984-443-6,103.3.60.59,443,192.168.10.16,52984,6,4/7/2017 10:08,4,2,0,...,-1,0,32,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
289743,192.168.10.5-104.106.246.231-53389-443-6,104.106.246.231,443,192.168.10.5,53389,6,4/7/2017 10:12,8757,3,1,...,0,1,20,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [10]:
def label_attack(df, label,start_time,end_time, attacker, victim):
    after = df[df['Timestamp'] >= start_time]
    before = df[df['Timestamp'] >= before_time]
    
    
    df[after&before]['Label'] = label 
    return df

In [12]:
df1['Label']=''
df1.head()

,Flowid,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Tot pkt,fwd pkt,bwd pkt,...,bytes mean est,fwd bytes mean est,bwd bytes mean est,len std,fwd len std,bwd len std,len std est,fwd len std est,bwd len std est,Label
115322,172.16.0.1-192.168.10.50-45422-80-6,172.16.0.1,45422,192.168.10.50,80,6,2017-07-04 10:30:03,7.000000,4.000000,3.000000,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,
24060,172.16.0.1-192.168.10.50-46276-22-6,172.16.0.1,46276,192.168.10.50,22,6,2017-07-04 14:09:01,57.000000,23.000000,34.000000,...,83.39,87.30,80.74,201.89,133.34,211.27,183.87,133.34,211.27,
47931,172.16.0.1-192.168.10.50-46278-22-6,172.16.0.1,46278,192.168.10.50,22,6,2017-07-04 14:09:01,57.000000,23.000000,34.000000,...,83.39,87.30,80.74,201.89,133.34,211.27,183.87,133.34,211.27,
181410,172.16.0.1-192.168.10.50-46280-22-6,172.16.0.1,46280,192.168.10.50,22,6,2017-07-04 14:09:01,56.000000,23.000000,33.000000,...,84.88,87.30,83.18,203.69,133.34,213.97,185.16,133.34,213.97,
211437,172.16.0.1-192.168.10.50-46282-22-6,172.16.0.1,46282,192.168.10.50,22,6,2017-07-04 14:09:01,57.000000,23.000000,34.000000,...,83.39,87.30,80.74,201.89,133.34,211.27,183.87,133.34,211.27,

In [13]:
###Brute Force